### PR TITLE
Added missing graphics files

### PR DESCRIPTION
**Pull request by paulpaterson**
**I'm not sure if this is going to work!**

These are the missing files from the previous pull. However, all the other changes are not in here. When I tried to merge with iminurnamez:master it reverts all my bingo changes because master includes the revert!

I think you may need to merge the bingo branch in the master and then merge this.

---

This is the UI redesign and the first fully playable version. The menu bar buttons are non functional but everything else should be working. 

Give it a try. Choose 5 bingo cards for a wild ride!

There are a ton of changes in here but only to bingo files. 

I'll clean up the graphics into sprite sheets in a subsequent pull.

### CODE REVIEW

**Comment by paulpaterson** [comment]
My previous note might not be clear ... here's the sequence,

1. I created a pull for many changes yesterday
2. This was accepted
3. Then it was reverted
4. I now added the missing files and pushed to my repo
5. Because the previous pull was accepted the only diffs are the added files
6. But the main repo master is now reverted so doesn't include my original changes in #1 above

Because of #6, if I try to merge the master back into my bingo branch then it blows away all my recent changes!

Let me know what I need to do to get this back in sync.

**Comment by Mekire** [comment]
Trying to figure it out currently...  Don't really understand why it doesn't see the difference in the repos.  Looking over cherry-pick but not sure if that is the right path.

**Comment by paulpaterson** [comment]
I'll have a go from my end and see if I can unravel it

**Comment by Mekire** [comment]
I think I know the answer, but your code still doesn't run on my end.  Please see the reddit thread I made for the traceback I am getting.


-Mek

**Pull request merged**
